from tkinter import *
top = Tk()
text = Text(top)
text.insert(INSERT, "Name.............")
text.insert(END, "Salary...........")
text.pack()
text.tag_add("write here", "1.0", "1.4")
text.tag_add("click here", "1.8", "1.13")
text.tag_config("write here", background="yellow", foreground="black")
text.tag_config("click here", background="black", foreground="white")
top.mainloop()
